---
title: "Data Exploration"
author: "Gianluca Scuri"
date: "2022-12-11"
output: html_document
---

## Setup e loading dataset

```{r}
set.seed(100)

# Setting librerie utili
# Package names
packages <- c("KFAS", "xts", "readxl", "fastDummies", "lubridate") 

# Install packages if not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))
```

```{r}
working_dir = dirname(rstudioapi::getSourceEditorContext()$path)
setwd(working_dir) # lo applica solo a questo chunk!

data <- read.csv("data2022_train.csv")
```

```{r}
POSIXct(data$X, format = "%Y%m%d  %H:%M:%OS", tz = "GMT")
POSIXct("2017-01-01 00:10:00", format = "%Y%m%d  %H:%M:%OS", tz = "GMT")
```

```{r}
summary(data)
```

```{r}

data$X <- as.Date(data$X, format = "%Y-%m-%d %H:%M:%S")

plot(data$y[seq(1, nrow(data), 144)], type = 'l')
plot(data$y[1:144], type = 'l')
```
